version: '3.9'

services:
  restapi:
    build: .
    restart: unless-stopped
    tty: true
    working_dir: /backendaccount
    environment:
      SERVICE_NAME: api2_development
      SERVICE_TAGS: development
    networks:
      - npm-nw
    deploy:
      mode: replicated
      replicas: 1
networks:
 npm-nw:
  external: true

